filter:
  excluded_paths:
    - 'tests/*'

build:
  environment:
    php: 7.3
  tests:
    override:
      - true
  nodes:
    analysis:
      dependencies:
        after:
          - vendor/bin/phpcs --config-set installed_paths ../../magento/magento-coding-standard/ # Scrutinizer does not run composer scripts
      tests:
        override:
          - php-scrutinizer-run
          - phpcs-run

